### ISSUE TITLE
Table pstone_purchase_payments  not created

### ISSUE THREAD

**Issue by andramil** [elBukkit/PreciousStones#134]
I have problem that table "pstone_purchase_payments" is not created. What coulms does it need?

Error from console:
` java.sql.SQLSyntaxErrorException: Table 'survi18_PreciousStones.pstone_purchase_payments' doesn't exist
[00:20:59 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
[00:20:59 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[00:20:59 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
[00:20:59 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1009)
[00:20:59 WARN]:        at PreciousStones-1.17.1.2 (1).jar//net.sacredlabyrinth.Phaed.PreciousStones.shaded.com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
[00:20:59 WARN]:        at PreciousStones-1.17.1.2 (1).jar//net.sacredlabyrinth.Phaed.PreciousStones.shaded.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
[00:20:59 WARN]:        at PreciousStones-1.17.1.2 (1).jar//net.sacredlabyrinth.Phaed.PreciousStones.storage.StorageManager.getPendingPurchases(StorageManager.java:1111)
[00:20:59 WARN]:        at PreciousStones-1.17.1.2 (1).jar//net.sacredlabyrinth.Phaed.PreciousStones.listeners.PSPlayerListener.onPlayerJoin(PSPlayerListener.java:101)
[00:20:59 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor172.execute(Unknown Source)
[00:20:59 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[00:20:59 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[00:20:59 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[00:20:59 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[00:20:59 WARN]:        at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:363)
[00:20:59 WARN]:        at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:305)
[00:20:59 WARN]:        at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:308)
[00:20:59 WARN]:        at net.minecraft.network.NetworkManager.a(NetworkManager.java:526)
[00:20:59 WARN]:        at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:201)
[00:20:59 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1636)
[00:20:59 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:480)
[00:20:59 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1470)
[00:20:59 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1264)
[00:20:59 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[00:20:59 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
`

**Comment by andramil** [comment]
im using 
`mysql  Ver 15.1 Distrib 10.3.31-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2`

I will try to upgrade to Mysql 8.0.28 today and check if it will help.

**Comment by andramil** [comment]
After changing MySQL to 8.0.28 it didn't helped a little.
