### ISSUE TITLE
Translocators dont work at all

### ISSUE THREAD

**Issue by xtomyserrax** [elBukkit/PreciousStones#8]
I got 2000 times this message:

[15:49:46] [Server thread/INFO]: xtomyserrax issued server command: /ps enable
[15:49:51] [Server thread/INFO]: xtomyserrax issued server command: /ps translocation import
[15:49:51] [Server thread/ERROR]: Error at SQL INSERT Query: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_UNIQUE]  A UNIQUE constraint failed (UNIQUE constraint failed: pstone_storedblocks.x, pstone_storedblocks.y, pstone_storedblocks.z, pstone_storedblocks.world)
...
[15:50:13] [Server thread/ERROR]: Error at SQL INSERT Query: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_UNIQUE]  A UNIQUE constraint failed (UNIQUE constraint failed: pstone_storedblocks.x, pstone_storedblocks.y, pstone_storedblocks.z, pstone_storedblocks.world)

I sadly dont know much about databases yet and we dont use it so its not a top priority. Idk if anyone knows why is this error happening and is able to fix it

**Comment by xtomyserrax** [comment]
[23:44:48] [Server thread/ERROR]: Error at SQL INSERT Query: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_UNIQUE]  A UNIQUE constraint failed (UNIQUE constraint failed: pstone_storedblocks.x, pstone_storedblocks.y, pstone_storedblocks.z, pstone_storedblocks.world)
[23:44:48] [Server thread/WARN]: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_UNIQUE]  A UNIQUE constraint failed (UNIQUE constraint failed: pstone_storedblocks.x, pstone_storedblocks.y, pstone_storedblocks.z, pstone_storedblocks.world)
[23:44:48] [Server thread/WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:941)
[23:44:48] [Server thread/WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:953)
[23:44:48] [Server thread/WARN]:        at org.sqlite.core.DB.throwex(DB.java:918)
[23:44:48] [Server thread/WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:953)
[23:44:48] [Server thread/WARN]:        at org.sqlite.core.DB.throwex(DB.java:918)
[23:44:48] [Server thread/WARN]:        at org.sqlite.core.NativeDB._exec_utf8(Native Method)
[23:44:48] [Server thread/WARN]:        at org.sqlite.core.NativeDB._exec(NativeDB.java:94)
[23:44:48] [Server thread/WARN]:        at org.sqlite.jdbc3.JDBC3Statement.executeUpdate(JDBC3Statement.java:109)
[23:44:48] [Server thread/WARN]:        at net.sacredlabyrinth.Phaed.PreciousStones.storage.SQLiteCore.insert(SQLiteCore.java:119)
[23:44:48] [Server thread/WARN]:        at net.sacredlabyrinth.Phaed.PreciousStones.managers.StorageManager.insertTranslocationBlock(StorageManager.java:1622)
[23:44:48] [Server thread/WARN]:        at net.sacredlabyrinth.Phaed.PreciousStones.managers.TranslocationManager.addBlock(TranslocationManager.java:119)
[23:44:48] [Server thread/WARN]:        at net.sacredlabyrinth.Phaed.PreciousStones.managers.TranslocationManager.addBlock(TranslocationManager.java:65)
[23:44:48] [Server thread/WARN]:        at net.sacredlabyrinth.Phaed.PreciousStones.managers.TranslocationManager.wipeTranslocationBlock(TranslocationManager.java:289)
[23:44:48] [Server thread/WARN]:        at net.sacredlabyrinth.Phaed.PreciousStones.translocation.TranslocationImporter.run(TranslocationImporter.java:84)
[23:44:48] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81)
[23:44:48] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400)
[23:44:48] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1036)
[23:44:48] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:406)
[23:44:48] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984)
[23:44:48] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824)
[23:44:48] [Server thread/WARN]:        at java.lang.Thread.run(Unknown Source)
