### ISSUE TITLE
MySQL error 

### ISSUE THREAD

**Issue by durajg01** [elBukkit/PreciousStones#92]
Hi, I have such a problem that after connecting the plug to the database I get this error

> [08:24:23] [Server thread/ERROR]: Error occurred while enabling PreciousStones v1.16.1.9 (Is it up to date?)
java.lang.IllegalStateException: Unable to initialise database
	at net.sacredlabyrinth.Phaed.PreciousStones.storage.StorageManager.<init>(StorageManager.java:76) ~[?:?]
	at net.sacredlabyrinth.Phaed.PreciousStones.PreciousStones.onEnable(PreciousStones.java:148) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.3.jar:git-Paper-247]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.3.jar:git-Paper-247]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.3.jar:git-Paper-247]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.3.jar:git-Paper-247]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.3.jar:git-Paper-247]
	at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.3.jar:git-Paper-247]
	at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:237) ~[patched_1.16.3.jar:git-Paper-247]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.3.jar:git-Paper-247]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-247]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Specified key was too long; max key length is 767 bytes
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_265]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_265]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_265]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_265]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:403) ~[patched_1.16.3.jar:git-Paper-247]
	at com.mysql.jdbc.Util.getInstance(Util.java:386) ~[patched_1.16.3.jar:git-Paper-247]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944) ~[patched_1.16.3.jar:git-Paper-247]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933) ~[patched_1.16.3.jar:git-Paper-247]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869) ~[patched_1.16.3.jar:git-Paper-247]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524) ~[patched_1.16.3.jar:git-Paper-247]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675) ~[patched_1.16.3.jar:git-Paper-247]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465) ~[patched_1.16.3.jar:git-Paper-247]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1915) ~[patched_1.16.3.jar:git-Paper-247]
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1254) ~[patched_1.16.3.jar:git-Paper-247]
	at net.sacredlabyrinth.Phaed.PreciousStones.shaded.com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44) ~[?:?]
	at net.sacredlabyrinth.Phaed.PreciousStones.shaded.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java) ~[?:?]
	at net.sacredlabyrinth.Phaed.PreciousStones.storage.TableCreator.execute(TableCreator.java:40) ~[?:?]
	at net.sacredlabyrinth.Phaed.PreciousStones.storage.TableCreator.addIndexes(TableCreator.java:223) ~[?:?]
	at net.sacredlabyrinth.Phaed.PreciousStones.storage.TableCreator.createSnitches(TableCreator.java:197) ~[?:?]
	at net.sacredlabyrinth.Phaed.PreciousStones.storage.TableCreator.createTables(TableCreator.java:30) ~[?:?]
	at net.sacredlabyrinth.Phaed.PreciousStones.storage.StorageManager.initiateDB(StorageManager.java:96) ~[?:?]
	at net.sacredlabyrinth.Phaed.PreciousStones.storage.StorageManager.<init>(StorageManager.java:74) ~[?:?]
	... 11 more
[08:24:23] [Server thread/INFO]: [PreciousStones] Disabling PreciousStones v1.16.1.9
[08:24:23] [Server thread/INFO]: [PreciousStones] Shutting Down: Cancelling all tasks...
[08:24:23] [Server thread/INFO]: [PreciousStones] Shutting Down: Saving all pending data...
[08:24:23] [Server thread/ERROR]: Error occurred while disabling PreciousStones v1.16.1.9 (Is it up to date?)
java.lang.NullPointerException: null
	at net.sacredlabyrinth.Phaed.PreciousStones.PreciousStones.onDisable(PreciousStones.java:225) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.3.jar:git-Paper-247]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.3.jar:git-Paper-247]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.3.jar:git-Paper-247]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384) ~[patched_1.16.3.jar:git-Paper-247]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.3.jar:git-Paper-247]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.3.jar:git-Paper-247]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.3.jar:git-Paper-247]
	at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.3.jar:git-Paper-247]
	at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:237) ~[patched_1.16.3.jar:git-Paper-247]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.3.jar:git-Paper-247]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-247]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]

And when you join and leave the game, this problem arises
https://prnt.sc/v7pgxf
https://prnt.sc/v7pi4y

**Comment by xtomyserrax** [comment]
Hey, could you please send me your database file? A248 made a fix for future new tables but I want to see your database so we can know if a migration could be easily done

**Comment by durajg01** [comment]
We are talking about data data from the version in which there was a bug, right?

If so, here is the link to the database: https://drive.google.com/file/d/1wf6Fh_-4lxAKtLKxCRdaY14wB20om3vC/view?usp=sharing
It is empty because, due to a bug, I didn't use the plugin




If I can change the subject for a while.
He wanted to make a proposal to change the / ps allow command so that if the argument 1 - [guest, coowner] is omitted, it automatically defaults to guest

**Comment by xtomyserrax** [comment]
Hey, if you dont have any data in your database, please download the latest version and let the plugin generate a new one as the bug is fixed.

About the allow command, anyone is welcome to make a PR to improve stuff so yeah! I can do that also. The reason I made it mandatory was because before, if players didnt add the argument, the default would be coowner and we got a lot of complaints saying that someone allowed had permissions to break fields, etc. But yeah we can make guest default

**Comment by durajg01** [comment]
https://prnt.sc/v8pghj
This error occurred while generating a new database


Sorry for my english, i use google translator


Edit --------------------------------
https://prnt.sc/v8pmz6 <- When turn off

**Comment by xtomyserrax** [comment]
Hey, could you please confirm me if version 1.16.1.12 works fine for you? I tested it in my test server with MySQL and now it works fine. https://jenkins.elmakers.com/job/PreciousStones/63/net.sacredlabyrinth.Phaed$PreciousStones/

Thank you!

**Comment by durajg01** [comment]
Hi, everything works. :D
If I find any errors, I will let you know :P

Thank You <3

I have one more command suggestion that can be added
in the command: / ps locations
When you hover the mouse over the plot line / name, you can add, for example, a command that, when clicked, will teleport to the plot and of course make it work for permissions

**Comment by xtomyserrax** [comment]
Hey, thank you for reporting and thanks to A248 who fixed this!

About suggestions, please make separate requests for each one. I really like that suggestion, it would be really useful and any dev is welcome to add something like that (ofc with the right configurations) ; Teleporting to a field block would be only useful for staff as it is usually under ground though
