### ISSUE TITLE
mysql error

### ISSUE THREAD

**Issue by mcastilloweb** [elBukkit/PreciousStones#94]
[22:21:51 WARN]: java.sql.SQLDataException: (conn=811451) Incorrect string value: '\xAC\xED\x00\x05sr...' for column `minecraft_survival16`.`pstone_players`.`uuid` at row 1
[22:21:51 WARN]: at com.github.beelzebu.lib.mariadb.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:167)
[22:21:51 WARN]: at com.github.beelzebu.lib.mariadb.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:110)
[22:21:51 WARN]: at com.github.beelzebu.lib.mariadb.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:228)
[22:21:51 WARN]: at com.github.beelzebu.lib.mariadb.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:216)
[22:21:51 WARN]: at com.github.beelzebu.lib.mariadb.MariaDbPreparedStatementClient.execute(MariaDbPreparedStatementClient.java:150)
[22:21:51 WARN]: at net.sacredlabyrinth.Phaed.PreciousStones.shaded.com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
[22:21:51 WARN]: at net.sacredlabyrinth.Phaed.PreciousStones.shaded.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
[22:21:51 WARN]: at net.sacredlabyrinth.Phaed.PreciousStones.storage.StorageManager.updatePlayer0(StorageManager.java:1299)
[22:21:51 WARN]: at net.sacredlabyrinth.Phaed.PreciousStones.storage.StorageManager.processPlayers(StorageManager.java:2375)
[22:21:51 WARN]: at net.sacredlabyrinth.Phaed.PreciousStones.storage.StorageManager.processQueue(StorageManager.java:2292)
[22:21:51 WARN]: at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99)
[22:21:51 WARN]: at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[22:21:51 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[22:21:51 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[22:21:51 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[22:21:51 WARN]: at java.base/java.lang.Thread.run(Thread.java:834)
[22:21:51 WARN]: Caused by: java.sql.SQLException: Incorrect string value: '\xAC\xED\x00\x05sr...' for column `minecraft_survival16`.`pstone_players`.`uuid` at row 1
[22:21:51 WARN]: Query is: INSERT INTO `pstone_players` (`player_name`, `uuid`, `last_seen`, `flags`) VALUES (?, ?, ?, ?) ON DUPLICATE KEY UPDATE last_seen = ?, flags = ?, parameters ['rlolyiyo2',<Serializable>,1603848111334,'{"density":8}',1603848111334,'{"density":8}']
[22:21:51 WARN]: at com.github.beelzebu.lib.mariadb.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:153)
[22:21:51 WARN]: at com.github.beelzebu.lib.mariadb.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:254)
[22:21:51 WARN]: at com.github.beelzebu.lib.mariadb.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:209)
[22:21:51 WARN]: ... 12 more

**Comment by A248** [comment]
`com.github.beelzebu.lib.mariadb` is another plugin shading the MariaDB JDBC driver. Are you using the Coins plugin by Beelzebu? You should talk to its author about both encapsulating that driver and updating it to the latest version.

**Comment by xtomyserrax** [comment]
Could you please confirm us if this newest version fixes the error? https://jenkins.elmakers.com/job/PreciousStones/63/net.sacredlabyrinth.Phaed$PreciousStones/
Thanks A248 for such a fast answer!

**Comment by xtomyserrax** [comment]
If you can, please confirm if it works fine now. Thanks! @mcastilloweb
